### ISSUE TITLE
Getting X509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by sarathcakurathi** [ericandrewlewis/kubernetes-via-terraform#1]
I am new to kubernetes, trying to configure it from terraform using these scripts. I created tls assets and copied to proper location as mentioned but when i try to issue kubectl get pods or kubectl get nodes I am getting x509 certificate signed by unknown authority error either from k8s master or from terraform. Please help me.

**Comment by ericandrewlewis** [comment]
Hi @sarathcakurathi,

sorry this setup is rather old at this point. I'd suggest finding a more up to date setup. I'm going to mark this as old  in the readme for future web surfers.
